### ISSUE TITLE
Question: How to change an attribute of an SVG element

### ISSUE THREAD

**Issue by Svantulden** [wonson/androidsvg#3]
Sorry, here I am again. 

I am trying to change the `fill` attribute of some elements in my SVG, but I can't seem to figure it out. I read [here](https://code.google.com/p/androidsvg/issues/detail?id=11#makechanges) that you use `save`  and `restore` to apply the changes, and I saw that I can use `svg.getElementById("idHere")` to get the `SvgObject`, but I can't seem to do anything with it since it is a protected class. 

Could you maybe explain how to change an attribute with this lib?

**Comment by wonson** [comment]
I m casting it to the real class (such as SVG.Group) which I expected. As you know, I m just patching it to implement DOM. Though I dun think its good implement for long term :P

**Comment by Svantulden** [comment]
Amazing, thanks! Yeah it's not really sustainable in the long run, and alot of boilerplate code, but I haven't found another library that allows editing and has this high of SVG compliance. 

I am now using this code for editing my SVG which works: 
```Java
holder.locationIconImageView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
            try
            {
                SVG svg = SVG.getFromResource(getActivity(), R.raw.junction);
                svg.setDocumentWidth("100%");
                svg.setDocumentHeight("100%");

                SVG.Circle border = (SVG.Circle)svg.getElementById("border");
                SVG.Style borderStyle = border.baseStyle;
                borderStyle.fill = new SVG.Colour(16777215);
                borderStyle.fillOpacity = 1.0f;

                SVG.Path droplet = (SVG.Path)svg.getElementById("droplet");
                SVG.Style dropletStyle = droplet.baseStyle;
                dropletStyle.stroke = new SVG.Colour(14540253);
                dropletStyle.strokeWidth = new SVG.Length(1.0f);

                svg.save();
                Drawable drawable = new PictureDrawable(svg.renderToPicture());
                holder.locationIconImageView.setImageDrawable(drawable);
            }
            catch(Exception e)
            {
                Log.d("SVGPARSE", "" + e.getMessage());
            }
```
Is that the way to go? 

Another thing I noticed, is that if a style property doesn't exist on the element, I cannot add it. For example, if a stroke property doesn't exist in the original SVG, setting `style.stroke = new SVG.Colour(14540253)` has no effect. Is there any way around this with this current fork? Or is it only possible to change properties and not add them? 

Thanks again for helping me out!

**Comment by wonson** [comment]
I m not the original project creator, so I don't know the what the "style" is. However, if you call "baseStyle", I think you'll get what you need. :)

**Comment by Svantulden** [comment]
Sorry I think I didn't use the right wording. I meant element attributes like `fill` and `stroke`. If an attribute doesn't exist on the original SVG yet, when I try to 'add' it by setting the `baseStyle.stroke` attribute for example, normally it would change the attribute when it is available. When it isn't available, it seems to not work when rendering.

**Comment by wonson** [comment]
Sounds weird. I wonder if it is the read write stream problem. 

Did you pull my commit 724bf6f5b051ece620fa172453dcc2e43a96b5c5 yesterday?

**Comment by wonson** [comment]
And also, save() and restore() is not this use. It's kinda like "push()" and "pop()" in openGL. I expect they will be in pair.

**Comment by wonson** [comment]
You may add attr in baseStyle now

**Comment by Svantulden** [comment]
Amazing, thanks alot for adding this!
